# Generated by Django 3.1.6 on 2021-02-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('idConta', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Saldo')),
                ('limiteSaqueDiario', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Limite de Saque Diário')),
                ('flagAtivo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipoConta', models.IntegerField(choices=[(1, 'Conta Corrente'), (2, 'Conta Poupanca'), (3, 'Conta Pagamento'), (4, 'Conta Salario')], verbose_name='Tipo de Conta')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('idPessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('idTransacao', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('dataTransacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('idConta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conta')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.AddField(
            model_name='conta',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa'),
        ),
    ]
