# Generated by Django 3.1.6 on 2021-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210211_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='tipoConta',
            field=models.IntegerField(choices=[(1, 'Conta Corrente'), (2, 'Conta Poupança'), (3, 'Conta Pagamento'), (4, 'Conta Salário')], verbose_name='Tipo de Conta'),
        ),
    ]
