# Generated by Django 3.1.6 on 2021-02-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210211_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Saque'), (2, 'Depósito')], null=True),
        ),
    ]
